### ISSUE TITLE
Td suelto sin contenido

### ISSUE THREAD

**Issue by manuelgom5** [Manuel-Gom/2022-23---practica-5-github---issues-Manuel-Gom#2]
https://github.com/Manuel-Gom/2022-23---practica-5-github---issues-Manuel-Gom/blob/3ddbb6b94f759b2c2085b8ad7027f14ca28bd7fa/errores.html#L63

Quita ese td

**Comment by Manuel-Gom** [comment]
gracias ya esta corregido.
